id: ID5524959
ocr_import_info:
  timestamp: '2023-04-04T12:08:33.518877+00:00'
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.8
  sponsor: Atisha
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.2
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-04-04 12:25:26.759197+00:00
last_modified: 2023-04-04 12:25:26.759202+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3421
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3421
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཛ་ཡ་ཨ་ནན་ཏའི་འཇུག་འགྲེལ།
  languages:
  - bo
  author: པཎྜི་ཏ་ཛ་ཡ་ཨ་ནནྟ།
statistics:
  ocr_word_mean_confidence_index: 0.9987660567248925
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN563:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN563
      total_pages: 648
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN563.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9987660567248925
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
